In [1]:
import numpy as np

# WX + B
1. W.T (generate w matrix with tranpose size of X matrix)
2. dot_product(X, W.T)
3. after dotproduct add biase (b)
4. at the end apply activation_function on each element
5. finally predict value of y_predict
6. calculate loss (y - y_predict)
7. update W and b values


# relu(dot(W, input) + b)

In [2]:
X = np.arange(24).reshape(6,4) # Input
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
W = np.random.randn(*X.shape) # Randomly generate weights w0
W = W.T # Transpose
W

array([[-0.60398992, -0.13048134, -1.189986  , -0.62705139, -0.54456251,
         1.9138559 ],
       [-1.46764135,  0.27582233, -1.33778821, -0.6125365 , -2.35296948,
         0.83194345],
       [ 0.59095401, -0.00902855, -0.77372899, -0.45838297,  0.84370595,
         0.59768421],
       [ 0.09509799, -0.73680765,  1.83827601,  0.00818909, -2.12512935,
         0.023562  ]])

In [6]:
step1 = np.dot(W,X) # dot_product (input, W.T)
step1

array([[ 11.99768788,  10.81547262,   9.63325737,   8.45104211],
       [-37.95809716, -42.62126693, -47.28443669, -51.94760646],
       [ 13.72643752,  14.51764117,  15.30884482,  16.10004847],
       [-21.67358309, -22.570395  , -23.46720692, -24.36401883]])

In [7]:
b = 2 #add biase , weight
step2 = step1 + b
step2

array([[ 13.99768788,  12.81547262,  11.63325737,  10.45104211],
       [-35.95809716, -40.62126693, -45.28443669, -49.94760646],
       [ 15.72643752,  16.51764117,  17.30884482,  18.10004847],
       [-19.67358309, -20.570395  , -21.46720692, -22.36401883]])

In [8]:
# apply relu function on step2
np.maximum(step2, 0) # Relu Function

array([[13.99768788, 12.81547262, 11.63325737, 10.45104211],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [15.72643752, 16.51764117, 17.30884482, 18.10004847],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

# Relu with Naive code

In [9]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [10]:
naive_relu(step2)

array([[13.99768788, 12.81547262, 11.63325737, 10.45104211],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [15.72643752, 16.51764117, 17.30884482, 18.10004847],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

# Add Element wise operation

In [10]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

a = np.arange(12).reshape(4,3)
b = a * 2
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [11]:
a + b

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [12]:
naive_add(a,b)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

# BroadCasting

In [13]:
a = np.arange(32*10).reshape(32,10)
b = np.arange(1*10).reshape(1,10)
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [14]:
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
a + b

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  32,  34,  36,  38,  40,  42,  44,  46,  48],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [150, 152, 154, 156, 158, 160, 162, 164, 166, 168],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178

In [16]:
epsilon = 0.5
def f(x, epsilon):
    return x + epsilon

x = 1
y = f(x , epsilon)
print(x+ epsilon,y)

1.5 1.5


In [17]:
def abc(x):
    return x + 2

#abc(abc(abc(2)))
abc(abc(abc(2)))
8

8

In [18]:
g = 2
step = 0.2

X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
w1 = W - step * g # g= gradient
w1

array([[-1.00398992, -0.53048134, -1.589986  , -1.02705139, -0.94456251,
         1.5138559 ],
       [-1.86764135, -0.12417767, -1.73778821, -1.0125365 , -2.75296948,
         0.43194345],
       [ 0.19095401, -0.40902855, -1.17372899, -0.85838297,  0.44370595,
         0.19768421],
       [-0.30490201, -1.13680765,  1.43827601, -0.39181091, -2.52512935,
        -0.376438  ]])