In [1]:
import numpy as np

# relu(dot(W, input) + b)

In [11]:
X = np.arange(24).reshape(6,4) # Input
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
W = np.random.randn(*X.shape) # Randomly generate weights
W = W.T
W

array([[ 0.98073457, -0.24480248,  0.40363147, -0.1419873 ,  0.53624579,
        -0.7315592 ],
       [-0.70436066,  0.10387092, -1.54047112,  0.50183881, -0.99858937,
        -0.85248181],
       [-1.49535921, -0.6704141 , -1.88440559, -0.12420751,  1.32509221,
        -0.60392374],
       [-1.81748535, -0.53157069,  0.54087214,  0.83835401,  1.74207787,
        -0.21149301]])

In [13]:
step1 = np.dot(W,X)
step1

array([[ -5.50525714,  -4.70299429,  -3.90073144,  -3.09846859],
       [-38.91328568, -42.40347891, -45.89367214, -49.38386537],
       [-10.12439077, -13.57760872, -17.03082667, -20.48404462],
       [ 35.90432819,  36.46508315,  37.02583811,  37.58659307]])

In [14]:
b = 2 #add biase , weight
step2 = step1 + b
step2

array([[ -3.50525714,  -2.70299429,  -1.90073144,  -1.09846859],
       [-36.91328568, -40.40347891, -43.89367214, -47.38386537],
       [ -8.12439077, -11.57760872, -15.03082667, -18.48404462],
       [ 37.90432819,  38.46508315,  39.02583811,  39.58659307]])

In [15]:
# apply relu function on step2
np.maximum(step2, 0) # Relu Function

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [37.90432819, 38.46508315, 39.02583811, 39.58659307]])

# Relu with Naive code

In [16]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [17]:
naive_relu(step2)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [37.90432819, 38.46508315, 39.02583811, 39.58659307]])

# Add Element wise operation

In [18]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

a = np.arange(12).reshape(4,3)
b = a * 2
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [19]:
a + b

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [20]:
naive_add(a,b)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

# BroadCasting

In [21]:
a = np.arange(32*10).reshape(32,10)
b = np.arange(1*10).reshape(1,10)
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [22]:
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
a + b

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  32,  34,  36,  38,  40,  42,  44,  46,  48],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [150, 152, 154, 156, 158, 160, 162, 164, 166, 168],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178